spring.datasource.url=jdbc:postgresql://localhost:5432/receitasdb
spring.datasource.username=postgres
spring.datasource.password=99137760

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloud-name=dolgckdlf
cloudinary.api-key=317623185327162
cloudinary.api-secret=Ke65p1y9EmkVth6KV4S5IlXDzW0